config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'admin', to: 'admin#index'
  get 'admin/courses'
  get 'admin/instructors'
  get 'admin/students'
  get 'admin/applies'
  get 'admin/offers'
  get 'admin/ta_matching'


  get 'offer_decision/decide'
  post 'offer_decision/accept'
  post 'offer_decision/reject'
  get 'offer_decision/thankyou'

  #get 'applies/index'
  
  #get 'students/basic_info'
  #get 'students/checkStatus'

  root 'welcome#index'
  get 'welcome/index'
  post 'welcome/login'
  get 'welcome/logout'
  get 'welcome/newStudent'
  post 'welcome/createStudent'

  resources :students do
    resources :applies
    get 'dashboard'
    #get 'basic_info'
    get 'checkStatus'
    get 'applyall'
    post 'updateApplyall'
  end

  resources :instructors do
    get 'dashboard'
    get 'courses'
    get 'applies'
    get 'checkStatus'
    get 'acceptOffer'
    get 'rejectOffer'
  end
  
  
  resources :courses do
    resources :offers do
      get 'send_email'
      post 'student_accept'
      post 'student_reject'
      post 'instructor_accept'
      post 'instructor_reject'
    end
    get 'candidates'
    post 'updateCandidates'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :course
  belongs_to :student
  validates :course_id, presence: true
  validates :student_id, presence: true
  validates :appType, presence: true
  validates :positive, inclusion: { in: [true, false] }
  validates :acceptAdjust, inclusion: { in: [true, false] }
  validates :takenBefore, inclusion: { in: [true, false] }
  
  enum appType: [ :ta, :senior_grader, :grader ]
  
end

app/controllers/applies_controller.rb
require 'time'
class AppliesController < ApplicationController
  def index
    @student = Student.find(params[:student_id])
    @applies = @student.applies
    #@sort = params[:sort]
    #@applies = @applies.order(@sort)
  end

  def show
    @apply = Apply.find(params[:id])
  end

  def new
    @student = Student.find(params[:student_id])
    @apply = @student.applies.new
    @courses = Course.all
    
  end

  def edit
    @student = Student.find(params[:student_id])
    @apply = Apply.find(params[:id])
  end

  def create
    @student = Student.find(params[:student_id])
    @apply = @student.applies.new(apply_params)
    if @apply.save
      flash[:notice] = "Apply was successfully saved."
      redirect_to student_applies_path
    else
      flash[:error] =  @apply.errors.messages
      render 'new'
    end
  end

  def update
    @student = Student.find(params[:student_id])
    @apply = Apply.find(params[:id])
    if @apply.update(apply_params)
      flash[:notice] = "Course was successfully updated."
      redirect_to student_applies_path
    else
      flash[:error] =  @apply.errors.messages
      render 'edit'
    end
  end

  def destroy
    @student = Student.find(params[:student_id])
    @apply = Apply.find(params[:id])
    @apply.destroy
    redirect_to student_applies_path
  end

  private
  def apply_params
    params.require(:apply).permit(:course_id, :appType, :priority, :positive, :acceptAdjust, :takenBefore, :grade)
  end
end

app/helpers/applies_helper.rb
module AppliesHelper

  # def appTypes_for_select
  #   (1..3).map {|i| [Apply.appTypeEnum(i), i]}
  #   # => [["TA", 1], ["Senor Grader", 2], ["Grader", 3]
  # end

  def booleans_for_select
    [["Yes", true], ["No", false]]
  end

  def booleanCaption(b)
    if b then
      'Yes'
    else
      'No'
    end
  end


end

app/views/applies/_form.html.erb
<%= form_for([@student, @apply]) do |f| %>
    <% if @apply.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@apply.errors.count, "error") %> prohibited this course from being saved:
          </h2>
          <ul>
            <% @apply.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <table>
      <tr>
        <td><%= f.label :course_id %></td>
        <td class="required">
          <%#= f.select :course_id  do %>
          <%# @courses.each do |cs| -%>
          <%#= content_tag(:option, cs.subject + cs.num.to_s + '-' + cs.section.to_s + '  ' + cs.title , value: cs.id) %>
          <%# end %>
          <%# end %>
          <%= f.select :course_id, courses_for_select %><%# see in app/helpers/courses_helper.rb %>
          <%#= f.collection_select :course_id, @courses, :id, :caption %>
        </td>
      </tr>

      <tr>
        <td><%= f.label :appType %></td>
        <td class="required"><%= f.select :appType, Apply.appTypes.keys.to_a %></td>
        <%# => appTypes_for_select = [["TA", 1], ["Senor Grader", 2], ["Grader", 3]] %>
        <%# => see in app/helpers/applies_helper.rb %>
      </tr>

      <tr>
        <td><%= f.label :priority %></td>
        <td class="required"><%= f.text_field :priority %></td>
      </tr>

      <tr>
        <td><%= f.label :positive %></td>
        <td class="required"><%= f.select :positive, booleans_for_select %></td>
      </tr>

      <tr>
        <td><%= f.label :acceptAdjust %></td>
        <td class="required"><%= f.select :acceptAdjust, booleans_for_select %></td>
      </tr>

      <tr>
        <td><%= f.label :takenBefore %></td>
        <td class="required"><%= f.select :takenBefore, booleans_for_select %></td>
      </tr>

      <tr>
        <td><%= f.label :grade %></td>
        <td class="required"><%= f.text_field :grade %></td>
      </tr>
    </table>
    <%= f.submit  :class=>"btn btn-success"%>
<% end %>

app/views/applies/edit.html.erb
<% content_for :body do %>
    <%= render 'form' %>
    <%= link_to 'Back', :back , {:class => "btn btn-primary"}%>
<% end %>

app/views/applies/index.html.erb
<% content_for :body do %>
    <h3> All Applications </h3>
    <p><%= link_to "new apply", new_student_apply_path(@student), {:class => "btn btn-primary"} %> </p>

    <p><%= link_to "Batch Apply", student_applyall_path(@student), {:class => "btn btn-primary"} %></p>

    <table class="table table-hover table-bordered">
      <tr>
        <th>Student</th>
        <th>Course</th>
        <th>Type</th>
        <th>Accept Adjust</th>
        <th>Created At</th>
        <th>Last modified</th>
        <th> edit</th>
        <th>delete</th>
      </tr>

      <% @applies.each do |apply| %>
          <tr>
            <td><%= apply.student.fullname %></td>
            <!--<td><%#= apply.course.subject %> <%#= apply.course.num %>-<%#= apply.course.section %> <%#= apply.course.title %> </td>-->
            <td><%= apply.course.caption %></td>
            <td><%= apply.appType %></td>
            <td><%= booleanCaption(apply.acceptAdjust) %></td>
            <td><%= apply.created_at %></td>
            <td><%= apply.updated_at %></td>
            <td><%= link_to "edit",  edit_student_apply_path(@student,apply)%></td>
            <td><%= link_to "delete", student_apply_path(@student,apply), method: :delete, data: {confirm: "Are you sure to delete?"}%></td>
          </tr>
      <% end %>

    </table>
<% end %>

app/views/applies/new.html.erb
<% content_for :body do %>
    <%= render 'form' %>
    <br>
    <%= link_to 'Back', :back , {:class => "btn btn-primary"}%>
<% end %>