config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'admin', to: 'admin#index'
  get 'admin/courses'
  get 'admin/instructors'
  get 'admin/students'
  get 'admin/applies'
  get 'admin/offers'
  get 'admin/ta_matching'


  get 'offer_decision/decide'
  post 'offer_decision/accept'
  post 'offer_decision/reject'
  get 'offer_decision/thankyou'

  #get 'applies/index'
  
  #get 'students/basic_info'
  #get 'students/checkStatus'

  root 'welcome#index'
  get 'welcome/index'
  post 'welcome/login'
  get 'welcome/logout'
  get 'welcome/newStudent'
  post 'welcome/createStudent'

  resources :students do
    resources :applies
    get 'dashboard'
    #get 'basic_info'
    get 'checkStatus'
    get 'applyall'
    post 'updateApplyall'
  end

  resources :instructors do
    get 'dashboard'
    get 'courses'
    get 'applies'
    get 'checkStatus'
    get 'acceptOffer'
    get 'rejectOffer'
  end
  
  
  resources :courses do
    resources :offers do
      get 'send_email'
      post 'student_accept'
      post 'student_reject'
      post 'instructor_accept'
      post 'instructor_reject'
    end
    get 'candidates'
    post 'updateCandidates'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    has_one :offer, dependent: :nullify
    has_many :applies
    has_many :courses, through: :applies
    validates :netID, presence: true
    validates :uin, presence: true
    validates_inclusion_of :uin, in: 100000000..999999999, :uniqueness => true
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, length: {maximum: 31}
    validates_email_format_of :email, :message => 'email address is not looking good'
  
  enum level: [ :MCS, :MSCS, :PHD ]
    
    
    def fullname
        first_name + " " + (middle_name || " ") + " " + last_name
    end
end

app/controllers/students_controller.rb
require 'date'
class StudentsController < ApplicationController

  http_basic_authenticate_with name: "admin", password: "admin", only: :index

  def index
    @students = Student.all
  end

  # def new
  #   @student = Student.new
  # end

  def checkStatus
    @student = Student.find(params[:student_id])
    @offer = @student.offer
    @offerPending = false
    @offerConfirmed = false
    if @offer
      @offerConfirmed = true
      case @offer.status
      when "sent"
        if @offer.student_accepted == false
          @status = "Rejected by student"
        elsif @offer.student_accepted == true
          @status =  "Accepted by student. Under review."
        else
          @offerPending = true
          @offerConfirmed = false
        end
      when "rejected"
        @status = "Rejected, final decision."
      when "accepted"
        @status = "Approved, final decision."
      else
        
      end
    end
  end

  # def basic_info
  #   @student = Student.find(params[:student_id])
  #   if(@student)
  #     redirect_to edit_student_path(@student)
  #   else
  #     #redirect_to new_student_path
  #     redirect_to welcome_logout_path
  #   end
  # end
  
  def edit
    @student = Student.find(params[:id])
  end

  # def create
  #   @student = Student.new(student_params)
  #   #@student.uin = session[:student_uin]
  #   @student.netID = session[:netID]
  #   @student.can_ta = true
  #   if @student.save
  #       flash[:notice] = "Basic information created successfully."
  #       redirect_to student_basic_info_path(@student)
  #   else
  #       flash[:error] = @student.errors.messages
  #       render 'new'
  #   end
  # end
  
  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      flash[:notice] = "Basic information was successfully updated."
      redirect_to edit_student_path(@student)
    else
      flash[:error] =  @student.errors.messages
      render 'edit'
    end
  end
  
  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end
  
  def show
    @student=Student.find(params[:id])
  end
  
  def dashboard
    @student = Student.find(params[:student_id])
    if @student.offer
      @notification = "You have pending TA decisions."
    else
      @notification = "No activities."
    end
  end
  
  def applyall
    @student = Student.find(params[:student_id])
    @applications = @student.applies
    @courses = Course.all
    @applyTypes = {}
    @applications.each do |apply|
        @applyTypes[apply.course.id] = apply.appType
    end
  end

  def updateApplyall
    @student = Student.find(params[:student_id])
    courseid2tp = params[:course]
    courseid2grade = params[:course_grade]
    #@prev_app = Apply.where(student_id: params[:student_id])
    @prev_app = @student.applies
    ids = []
    Apply.where(student_id:params[:student_id]).destroy_all
    courseid2tp.each {|cid,type|
      # puts("course_id:" + k.to_s + "  type:" + v.to_s + "  grade:" + courseid2grade[k])
      if (type != "none")
        taken = false
        grade = "Not Taken"
        if (courseid2grade[cid] != "Not Taken")
          taken = true
          grade = courseid2grade[cid]
        end
        napp = @student.applies.new(course_id:cid, student:@student, appType:type, priority:1,
                  acceptAdjust:true, takenBefore:taken, grade:grade, positive:true)
        ids << napp.save
      end
    }
    
    if puts(ids.include? false)
        flash[:error] = "Updated Applications failed."
        redirect_to student_applyall_path(@student.id)
    else
        flash[:notice] = "Updated Applications successfully"
        redirect_to student_applyall_path(@student.id)
    end
  end
  
  
private
    def student_params
      params.require(:student).permit(
        :level,
        :date_enrolled,
        :first_name, 
        :middle_name, 
        :last_name,
        :email, 
        :advisor_email,
        :phone,
        :perferences)
        
    end
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
    def students_for_select
        Student.all.collect {|s| [ s.fullname, s.id ] }
    end
    
    def currentStudent
            Student.find_by_netID(session[:netID])
    end
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f|  %>

    <% if @student.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@student.errors.count, "error") %> prohibited this course from being saved:
        </h2>
        <ul>
          <% @student.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      
      
    <table>
      <tr>
        <td><%= f.label :level %></td>
        <td class="required"><%= f.select :level, options_for_select([["Master Non-Thesis", "MCS"], ["Thesis Master", "MSCS"], ["PhD", "PHD"]], @student.level) %></td>
      </tr>
      <tr>
        <td><%= f.label :date_enrolled %></td>
        <!--<td class="required"><%#= date_select :student, :date_enrolled, default: {year: eval(@student.date_enrolled)[1], month: eval(@student.date_enrolled)[2], day: eval(@student.date_enrolled)[3]} %></td>-->
        <td class="required"><%= f.date_field :date_enrolled, value: @student.date_enrolled %></td>
      </tr>

      <tr>
        <td><%= f.label :first_name %></td>
        <td class="required"><%= f.text_field :first_name %></td>
        <td><%= f.label :middle_name %></td>
        <td> <%= f.text_field :middle_name %></td>
        <td> <%= f.label :last_name %></td>
        <td class="required"> <%= f.text_field :last_name %></td>
      </tr>
      <tr>
        <td><%= f.label :email %></td>
        <td class="required"><%= f.text_field :email %></td>
      </tr>

      <tr>
        <td><%= f.label :phone %></td>
        <td class="required"><%= f.text_field :phone %></td>
      </tr>

      <tr>
        <td> <%= f.label :advisor_email %></td>
        <td class="required"> <%= f.text_field :advisor_email %></td>
      </tr>
      <tr>
        <td><%= f.label :perferences %></td>
        <td> <%= f.text_area  :perferences %></td>
      </tr>
    </table>
    <%= f.submit "update student", :class=>"btn btn-success"%>
<% end %>

app/views/students/applyall.erb
<% content_for :body do %>

  <p><%= @student.fullname %></p>
  <hr>
  <p>Applied:</p>
    <table class="table table-hover table-bordered">
      <tr>
        <th>Course</th>
        <th>Type</th>
        <th>Grade</th>
        <th>Last modified</th>
      </tr>

      <% @prev_app.each do |apply| %>
          <tr>
            <!--<td><%#= apply.course.subject %> <%#= apply.course.num %>-<%#= apply.course.section %> <%#= apply.course.title %> </td>-->
            <td><%= apply.course.caption %></td>
            <td><%= apply.appType %></td>
            <td><%= apply.grade %></td>
            <td><%= apply.updated_at %></td>
          </tr>
      <% end %>
    
    
    </table>
    <hr>
    <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Subject</th>
        <th>No.</th>
        <th>Sec</th>
        <th>Title</th>
        <th>Apply</th>
        <td>Grade</td>
      </tr>
    </thead>

<%= form_tag student_updateApplyall_path(@student), method: "post" do %>

    <% @courses.each do |course| %>
      <tr>
        <td><%= course.subject %></td>
        <td><%= course.num %></td>
        <td><%= course.section %></td>
        <td><%= course.title %></td>
        <td>
            <%= radio_button_tag "course[#{course.id}]", "none", @appty[course.id] =="none" %>
            <%= label_tag "course[#{course.id}]", 'none' %>
            <% Apply.appTypes.keys.each do |type| %>
                <%= radio_button_tag "course[#{course.id}]", type, @appty[course.id] == type %>
                <%= label_tag "course[#{course.id}]", type %>
            <% end %>
        </td>
        <td>
          <%= select_tag "course_grade[#{course.id}]", options_for_select(["Not Taken", "A", "B", "Others"]) %>
        </td>
      </tr>
    <% end %>
  </table>

<p><%= submit_tag "Update" %></p>
<% end %>
<hr>
<%= link_to 'Back', courses_path %>
<% end %>

app/views/students/applyall.html.erb
<% content_for :body do %>

  <p><%= @student.fullname %></p>
  <hr>
  <p>Applied:</p>
    <table class="table table-hover table-bordered">
      <tr>
        <th>Course</th>
        <th>Type</th>
        <th>Grade</th>
        <th>Last modified</th>
      </tr>

      <% @applications.each do |apply| %>
          <tr>
            <td><%= apply.course.caption %></td>
            <td><%= apply.appType %></td>
            <td><%= apply.grade %></td>
            <td><%= apply.updated_at %></td>
          </tr>
      <% end %>
    
    
    </table>
    <hr>
    
<%= form_tag student_updateApplyall_path(@student), method: "post" do %>
    <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Course</th>
        <th>Apply</th>
        <td>Grade</td>
      </tr>
    </thead>

    <% @courses.each do |course| %>
      <tr>
        <td><%= course.caption %></td>
        <td>
            <%= radio_button_tag "course[#{course.id}]", "none", @applyTypes[course.id] == "none" %>
            <%= label_tag "course[#{course.id}]", 'none' %>
            <% Apply.appTypes.keys.each do |type| %>
                <%= radio_button_tag "course[#{course.id}]", type, @applyTypes[course.id] == type %>
                <%= label_tag "course[#{course.id}]", type %>
            <% end %>
        </td>
        <td>
          <%= select_tag "course_grade[#{course.id}]", options_for_select(["Not Taken", "A", "B", "Others"]) %>
        </td>
      </tr>
    <% end %>
  </table>

<p><%= submit_tag "Update" %></p>
<% end %>
<hr>
    <%= link_to 'Back', :back , {:class => "btn btn-primary"}%>
<% end %>

app/views/students/checkStatus.html.erb
<% content_for :body do %>
<p>Your pending offer.</p>
<table class="table table-hover table-bordered">
    <tr>
        <th>Course</th>
        <th>Type</th>
        <th>Instructor</th>
        <th colspan="2">Actions</th>
    </tr>
    <% if @offerPending %>
    <tr>
        <td><%= @offer.course.caption %></td>
        <td><%= @offer.app_type %></td>
        <% if @offer.course.instructor %>
            <td><%= @offer.course.instructor.fullname %></td>
        <% else %>
            <td class="btn-warning">TBA</td>
        <% end %>
        <td><%= button_to "Accept",  course_offer_student_accept_path(@offer.course, @offer) %></th>
        <td><%= button_to "Reject",  course_offer_student_reject_path(@offer.course, @offer) %></th>
    </tr>
    <% end %>
</table>
<p>Your confirmed offer.</p>
<table class="table table-hover table-bordered">
    <tr>
        <th>Course</th>
        <th>Type</th>
        <th>Instructor</th>
        <th>Status</th>
    </tr>
    <% if @offerConfirmed %>
    <tr>
        <td><%= @offer.course.caption %></td>
        <td><%= @offer.app_type %></td>
        <% if @offer.course.instructor %>
            <td><%= @offer.course.instructor.fullname %></td>
        <% else %>
            <td class="btn-warning">TBA</td>
        <% end %>
        <td><%= @status %></td>
    </tr>
    <% end %>
</table>
<% end %>

app/views/students/dashboard.html.erb
<% content_for :body do %>
<p>Hello, <%= @student.fullname %>.</p>
<p>Your NetID is <%= @student.netID %>.</p>
<p><%= @notification %></p>
<% end %>

app/views/students/edit.html.erb
<% content_for :body do %>
<%= render 'form' %>
    <br>
<%= link_to 'Back', students_path , {:class => "btn btn-primary"}%>
<% end %>

app/views/students/index.csv.erb
<%- headers = ['UIN', 'First Name', 'Middle Name', 'Last Name', 'Email', 'Phone', 'Level', 'Advisor Email', 'Date Enrolled'] -%>
<%= CSV.generate_line headers %>
<%- @students.each do |obj| -%>
<%= CSV.generate_line([obj.uin, obj.first_name, obj.middle_name || "", obj.last_name, obj.email, obj.phone, obj.level, obj.advisor_email, obj.date_enrolled]).html_safe -%>
<%- end -%>

app/views/students/index.html.erb
<% content_for :body do %>
<h1>All student</h1>

<p><%= link_to 'Download CSV list', students_path(format: :csv), {:class => "btn btn-primary"} %></p>

<table class="table table-bordered">
 <tr>
    <th>Name</th>
    <th>UIN</th>
    <th>NetID</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Date Enrolled</th>
    <!--<th>Details</th>-->
    <th>Edit</th>
  </tr>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.fullname %></td>
      <td><%= student.uin %></td>
      <td><%= student.netID %></td>
      <td><%= student.email %></td>
      <td><%= student.phone %></td>
      <td><%= student.date_enrolled %></td>
      <!--<td><%#= link_to 'Show', student_path(student) %></td>-->
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are your sure to delete?' } %></td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/students/new.html.erb
<!--html:{class: "form-inline"},-->
<% content_for :body do %>
<%= render 'form' %>
<%= link_to 'Back', students_path, {:class => "btn btn-primary"} %>
<% end %>

app/views/students/show.html.erb
<% content_for :body do %>
<%= render 'form' %>
    <br>
<%= link_to 'Back', students_path, {:class => "btn btn-primary"} %>
<% end %>