config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'admin', to: 'admin#index'
  get 'admin/courses'
  get 'admin/instructors'
  get 'admin/students'
  get 'admin/applies'
  get 'admin/offers'
  get 'admin/ta_matching'


  get 'offer_decision/decide'
  post 'offer_decision/accept'
  post 'offer_decision/reject'
  get 'offer_decision/thankyou'

  #get 'applies/index'
  
  #get 'students/basic_info'
  #get 'students/checkStatus'

  root 'welcome#index'
  get 'welcome/index'
  post 'welcome/login'
  get 'welcome/logout'
  get 'welcome/newStudent'
  post 'welcome/createStudent'

  resources :students do
    resources :applies
    get 'dashboard'
    #get 'basic_info'
    get 'checkStatus'
    get 'applyall'
    post 'updateApplyall'
  end

  resources :instructors do
    get 'dashboard'
    get 'courses'
    get 'applies'
    get 'checkStatus'
    get 'acceptOffer'
    get 'rejectOffer'
  end
  
  
  resources :courses do
    resources :offers do
      get 'send_email'
      post 'student_accept'
      post 'student_reject'
      post 'instructor_accept'
      post 'instructor_reject'
    end
    get 'candidates'
    post 'updateCandidates'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
    has_many :courses, dependent: :nullify
    has_many :offers, through: :courses
    has_many :applies, through: :courses
    validates :first_name, presence: true, length: { minimum: 3, maximum: 127}
    validates :last_name, presence: true, length: { minimum: 3, maximum: 127}
    validates :email, presence: true, length: { minimum: 3, maximum: 127}, :email_format => { :message => 'is not looking good' }
    validates :netID, presence: true
    validates :uin, presence: true
    validates_inclusion_of :uin, in: 100000000..9999999999


  
    def fullname
        first_name + " " + (middle_name || "") + " " + last_name
    end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  def index
    @instructors = Instructor.all.order(:last_name)
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def new
    @instructor = Instructor.new
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    redirect_to instructors_path
  end

  def create
    # render plain: params[:instructor].inspect
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      flash[:notice] = "Instructor was successfully saved."
      redirect_to instructors_path
    else
      flash[:error] =  @instructor.errors.messages
      render 'new'
    end
  end

  def update
    @instructor = Instructor.find(params[:id])

    if @instructor.update(instructor_params)
      flash[:notice] = "Instructor was successfully updated."
      redirect_to instructors_path
    else
      flash[:error] =  @instructor.errors.messages
      render 'edit'
    end
  end

  def dashboard
    @instructor = Instructor.find(params[:instructor_id])
  end

  def courses
    @instructor = Instructor.find(params[:instructor_id])
    @courses = @instructor.courses.order(:num)
  end

  def applies
    @instructor = Instructor.find(params[:instructor_id])
    @applies = @instructor.applies
  end

  def checkStatus
    @instructor = Instructor.find(params[:instructor_id])
    @offers = @instructor.offers
    @offerPending = false
    @offerConfirmed = false

    # if @offer
    #   @offerConfirmed = true
    #   case @offer.status
    #     when "sent"
    #       if @offer.instructor_accepted == false
    #         @status = "Rejected by instructor"
    #       elsif @offer.instructor_accepted == true
    #         @status =  "Accepted by instructor. Under review."
    #       else
    #         @offerPending = true
    #         @offerConfirmed = false
    #       end
    #     when "rejected"
    #       @status = "Rejected, final decision."
    #     when "accepted"
    #       @status = "Approved, final decision."
    #     else
    #
    #   end
    # end
  end

  def acceptOffer

  end

  def rejectOffer

  end

  private
  def instructor_params
    params.require(:instructor).permit(:first_name, :middle_name, :last_name, :email, :uin, :netID)
  end

end

app/helpers/instructors_helper.rb
module InstructorsHelper
    def instructors_for_select
        Instructor.all.collect {|instructor| [ instructor.fullname, instructor.id ] }
    end
    
    def currentInstructor
            Instructor.find_by_netID(session[:netID])
    end

    def offerPending(offer)
        offer.status == "sent" and (!offer.instructor_accepted or !offer.student_accepted)
    end

    def offerProcessed(offer)
        offer.instructor_accepted or offer.student_accepted
    end
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
    <% if @instructor.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@instructor.errors.count, "error") %> prohibited this course from being saved:
        </h2>
        <ul>
          <% @instructor.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      
    <table>
      <tr>
        <td><%= f.label :first_name %></td>
        <td class="required"><%= f.text_field :first_name %></td>
      </tr>
      
      <tr>
        <td><%= f.label :middle_name %></td>
        <td><%= f.text_field :middle_name %></td>
      </tr>
      
      <tr>
        <td><%= f.label :last_name %></td>
        <td class="required"><%= f.text_field :last_name %></td>
      </tr>
      
      <tr>
        <td><%= f.label :email %></td>
        <td class="required"><%= f.text_field :email %></td>
      </tr>

      <tr>
        <td><%= f.label :uin %></td>
        <td class="required"><%= f.number_field :uin, in: 100000000..999999999 %></td>
      </tr>
      
      <tr>
        <td><%= f.label :netID %></td>
        <td class="required"><%= f.text_field :netID %></td>
      </tr>
    </table>
    <%= f.submit :class=>"btn btn-success"%>
<% end %>

app/views/instructors/applies.html.erb
<% content_for :body do %>
    <h3> All Applications to your courses </h3>
    <table class="table table-hover table-bordered">
      <tr>
        <th>Student</th>
        <th>Course</th>
        <th>Type</th>
        <th>Accept Adjust</th>
        <th>Created At</th>
        <th>Last modified</th>
      </tr>

      <% @applies.each do |apply| %>
          <tr>
            <td><%= apply.student.fullname %></td>
            <!--<td><%#= apply.course.subject %> <%#= apply.course.num %>-<%#= apply.course.section %> <%#= apply.course.title %> </td>-->
            <td><%= apply.course.caption %></td>
            <td><%= apply.appType %></td>
            <td><%= booleanCaption(apply.acceptAdjust) %></td>
            <td><%= apply.created_at %></td>
            <td><%= apply.updated_at %></td>
          </tr>
      <% end %>

    </table>
<% end %>

app/views/instructors/checkStatus.html.erb
<% content_for :body do %>
    <p>Your pending offer.</p>
    <table class="table table-hover table-bordered">
      <tr>
        <th>Course</th>
        <th>Type</th>
        <th>Student</th>
        <th colspan="2">Actions</th>
      </tr>

      <% @offers.each do |offer| %>
          <% if offerPending(offer) %>
              <tr>
                <td><%= offer.course.caption %></td>
                <td><%= offer.app_type %></td>
                <% if offer.student %>
                    <td><%= offer.student.first_name %> <%= offer.student.last_name %></td>
                <% else %>
                    <td class="btn-warning">TBA</td>
                <% end %>
                <td><%= button_to "Accept",  course_offer_instructor_accept_path(offer.course, offer) %></td>
                <td><%= button_to "Reject",  course_offer_instructor_accept_path(offer.course, offer) %></td>
              </tr>
          <% end %>
      <% end %>
    </table>

    <p>Your processed offer.</p>
    <table class="table table-hover table-bordered">
      <tr>
        <th>Course</th>
        <th>Type</th>
        <th>Student</th>
        <th>Status</th>
      </tr>
      <% @offers.each do |offer| %>
          <% if offerProcessed(offer) %>
              <tr>
                <td><%= offer.course.caption %></td>
                <td><%= offer.app_type %></td>
                <% if offer.student %>
                    <td><%= offer.student.first_name %> <%= offer.student.last_name %></td>
                <% else %>
                    <td class="btn-warning">TBA</td>
                <% end %>
                <td><%= offer.status %></td>
              </tr>
          <% end %>
      <% end %>
    </table>
<% end %>

app/views/instructors/courses.html.erb
<% content_for :body do %>
<div class = "table">
  <h1>Courses you teach in this semester</h1>
  <table class="table table-hover table-bordered">
    <thead>
      <tr>
        <th>Subject</th>
        <th>No.</th>
        <th>Sec</th>
        <th>Title</th>
        <th>Action</th>
      </tr>
    </thead>
   
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.subject %></td>
        <td><%= course.num %></td>
        <td><%= course.section %></td>
        <td><%= course.title %></td>
        <td><%= link_to 'Choose TAs', course_candidates_path(course) %></td>
      </tr>
    <% end %>
  </table>
</div>
<% end %>

app/views/instructors/dashboard.html.erb
<% content_for :body do %>
<h1>Hello, <%= @instructor.fullname %>.</h1>
<% end %>

app/views/instructors/edit.html.erb
<% content_for :body do %>
<%= render 'form' %>
    <br>
<%= link_to 'Back', instructors_path, {:class => "btn btn-primary"} %>
<% end %>

app/views/instructors/index.csv.erb
<%- headers = ['First Name', 'Middle Name', 'Last Name', 'UIN', 'NetID', 'Email'] -%>
<%= CSV.generate_line headers %>
<%- @instructors.each do |inst| -%>
<%= CSV.generate_line([inst.first_name, inst.middle_name, inst.last_name, inst.uin, inst.netID, inst.email]) -%>
<%- end -%>

app/views/instructors/index.html.erb
<% content_for :body do %>
  <h1>All instructors</h1>
  <!--<p>Find me in app/views/instructor/index.html.erb</p>-->
  
<%= link_to 'Download CSV list', instructors_path(format: :csv), {:class => "btn btn-primary"} %>

<%= link_to 'New instructor', new_instructor_path , {:class => "btn btn-primary"}%>
  
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>UIN</th>
        <th>NetID</th>
        <th>Courses</th>
        <!--<th>Action</th>-->
      </tr>
    </thead>
  
  <% @instructors.each do |instructor| %>
    <tr>
      <td><%= instructor.first_name %></td>
      <td width=80><%= instructor.middle_name %></td>
      <td><%= instructor.last_name %></td>
      <td><%= instructor.email %></td>
      <td><%= instructor.uin %></td>
      <td><%= instructor.netID %></td>
      <td><%= link_to instructor.courses.length, instructor_courses_path(instructor) %></td>
      <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
      <td><%= link_to 'Delete', instructor_path(instructor), method: :delete, data: { confirm: 'Are you sure to delete?' } %></td>
    </tr>
    <% end %>
  </table>

<% end %>

app/views/instructors/new.html.erb
<% content_for :body do %>
<%= render 'form' %>
    <br>
<%= link_to 'Back', instructors_path, {:class => "btn btn-primary"} %>
<% end %>

app/views/instructors/show.html.erb
<% content_for :body do %>
<%= render 'form' %>
<%= link_to 'Back', instructors_path %>
<% end %>