config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'
  get 'admin', to: 'admin#index'
  get 'admin/courses'
  get 'admin/instructors'
  get 'admin/students'
  get 'admin/applies'
  get 'admin/offers'
  get 'admin/ta_matching'


  get 'offer_decision/decide'
  post 'offer_decision/accept'
  post 'offer_decision/reject'
  get 'offer_decision/thankyou'

  #get 'applies/index'
  
  #get 'students/basic_info'
  #get 'students/checkStatus'

  root 'welcome#index'
  get 'welcome/index'
  post 'welcome/login'
  get 'welcome/logout'
  get 'welcome/newStudent'
  post 'welcome/createStudent'

  resources :students do
    resources :applies
    get 'dashboard'
    #get 'basic_info'
    get 'checkStatus'
    get 'applyall'
    post 'updateApplyall'
  end

  resources :instructors do
    get 'dashboard'
    get 'courses'
    get 'applies'
    get 'checkStatus'
    get 'acceptOffer'
    get 'rejectOffer'
  end
  
  
  resources :courses do
    resources :offers do
      get 'send_email'
      post 'student_accept'
      post 'student_reject'
      post 'instructor_accept'
      post 'instructor_reject'
    end
    get 'candidates'
    post 'updateCandidates'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_adminmenu.html.erb
    <ul class="nav nav-pills flex-column">
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Dashboard", admin_index_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Courses", admin_courses_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Instructors", admin_instructors_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Students", admin_students_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "All applications", admin_applies_path %></a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link"><%= link_to "All offers", admin_offers_path %></a>
      </li>
    </ul>

app/views/layouts/_insmenu.html.erb
    <ul class="nav nav-pills flex-column">
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Dashboard", instructor_dashboard_path(currentInstructor) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Edit your information", edit_instructor_path(currentInstructor) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Your Courses", instructor_courses_path(currentInstructor) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Applies to your courses", instructor_applies_path(currentInstructor) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Offers to your courses", instructor_checkStatus_path(currentInstructor) %></a>
      </li>
    </ul>

app/views/layouts/_nonemenu.html.erb
<ul class="nav nav-pills flex-column">
</ul>

app/views/layouts/_stumenu.html.erb
    <ul class="nav nav-pills flex-column">
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Home", student_dashboard_path(currentStudent) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Basic Info", edit_student_path(currentStudent) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Apply", student_applies_path(currentStudent) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Check Application Status", student_checkStatus_path(currentStudent) %></a>
      </li>
    </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HelloWorld</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-custom fixed-top">
    <a class="navbar-brand" href="#">TA Application System</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto"></ul>
      <p class="navbar-nav mr-sm-2" style="color:white">You logged in as <%= session[:user_type] %></p>
      <%= link_to 'Logout', welcome_logout_path, {:class=>"btn btn-outline-secondary my-2 my-sm-0"} %>
      <!--<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Sign In</button>-->
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar" id="side-nav-bar">
        <%= render usernav%> <%# see in app/helpers/application_helper.rb %>
      </nav>
  
      <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">
        <p class="notice"><%= flash[:notice] %></p>
        <p class="alert"><%= flash[:error] %></p>
        <%= yield :body %>
      </main>
    </div>
  </div>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>